# Generated by Django 5.2.8 on 2025-11-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="prise",
            new_name="price",
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Добавьте изображение продукта",
                null=True,
                upload_to="images",
                verbose_name="Изображение",
            ),
        ),
    ]
