# Generated by Django 5.2.8 on 2025-11-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_rename_prise_product_price_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Добавьте изображение продукта",
                null=True,
                upload_to="media/images",
                verbose_name="Изображение",
            ),
        ),
    ]
