# Generated by Django 5.2.8 on 2025-11-24 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Добавьте изображение продукта",
                null=True,
                upload_to="images",
                verbose_name="Изображение",
            ),
        ),
    ]
